"""Add is_exported to QueryLog

Revision ID: b3b67ecb7608
Revises: 740d18faec6d
Create Date: 2026-03-29 17:04:19.414925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b67ecb7608'
down_revision: Union[str, Sequence[str], None] = '740d18faec6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('is_exported', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'is_exported')
    # ### end Alembic commands ###
